username: GitHub-CI
icon_url: https://octodex.github.com/images/mona-the-rivetertocat.png

pretext: "Daily open pull requests for org {{ env.ORG_NAME }}"
title: "Daily Open PRs"
title_link: "{{workflowRunUrl}}"

text: |
  {{ env.PR_REPORT }}

fallback: |-
  [GitHub] Daily open PRs report for {{ env.ORG_NAME }}

fields:
  - title: Workflow
    value: "<{{workflowUrl}}|{{workflow}}>"
    short: true
  - title: Run Number
    value: "{{runNumber}}"
    short: true
  - title: Actor
    value: "{{actor}}"
    short: true

footer: >-
  <{{repositoryUrl}}|{{repositoryName}}> {{workflow}} #{{runNumber}}

colors:
  success: "#0F9D58"
  failure: "#DB4437"
  cancelled: "#E66C40"
  default: "#4285F4"

icons:
  success: ":white_check_mark:"
  failure: ":grimacing:"
  cancelled: ":x:"
  skipped: ":heavy_minus_sign:"
  default: ":interrobang:"
